<?php

return [
   "activities" => [],
   'bible_verses' => 'C:\\sites\\github\\bible_index.json',
   'bible_highlights' => [],
   "media" => [],
   "library_chapter_sections" => [],
   "library_books" => [],
   "library_book_chapters" => [],
   "libraries" => [],
   "lessons" => [],
   "series" => [],
   "tags" => [
      ['value'=>'discipline', 'object_id'=>1, 'object_class'=>'BibleVerse'],
      ['value'=>'fasting', 'object_id'=>1, 'object_class'=>'BibleVerse'],
      ['value'=>'food', 'object_id'=>1, 'object_class'=>'BibleVerse'],
      ['value'=>'self denial', 'object_id'=>1, 'object_class'=>'BibleVerse'],
      ['value'=>'grace', 'object_id'=>1, 'object_class'=>'BibleVerse'],
      ['value'=>'faith', 'object_id'=>2, 'object_class'=>'BibleVerse'],
      ['value'=>'mercy', 'object_id'=>2, 'object_class'=>'BibleVerse'],
      ['value'=>'peace', 'object_id'=>2, 'object_class'=>'BibleVerse'],
      ['value'=>'hope', 'object_id'=>3, 'object_class'=>'BibleVerse'],
      ['value'=>'featured', 'object_id'=>3, 'object_class'=>'BibleVerse'],
      ['value'=>'osas', 'object_id'=>3, 'object_class'=>'BibleVerse'],
      ['value'=>'salvation', 'object_id'=>3, 'object_class'=>'BibleVerse']
   ],
   "courses" => [],
   "comments" => [],
   "classrooms" => [],
    "roles" => [],
    "role_user" => [],
    "permission_role" => [],
    "permissions" => [],
   "ministries" => [
        ['id' => 1, 'title' =>'Deliverance Center','config'=>'{}','user_id'=>3,'show_home_page'=>true]
   ],
   "notifications" => [],
    'SCRIPTURE' => [
      env('SEED_SCRIPTURE') . '/bible_version_key.sql',
      env('SEED_SCRIPTURE') . '/key_abbreviations_english.sql',
      env('SEED_SCRIPTURE') . '/key_english.sql',
      env('SEED_SCRIPTURE') . '/key_genre_english.sql',
      env('SEED_SCRIPTURE') . '/t_kjv.sql',
      env('SEED_SCRIPTURE') . '/t_asv.sql',
      env('SEED_SCRIPTURE') . '/t_bbe.sql',
      env('SEED_SCRIPTURE') . '/t_dby.sql',
      env('SEED_SCRIPTURE') . '/t_wbt.sql',
      env('SEED_SCRIPTURE') . '/t_web.sql',
      env('SEED_SCRIPTURE') . '/t_ylt.sql'
    ],
    'NOTES' => env('SEED_NOTES'),
    "AUTHORITIES" => env('SEED_AUTHORITIES'),
    "CLIENTS" => env('SEED_CLIENTS'),
    "LINKS" => env('SEED_LINKS'),
    "LRS" => env('SEED_LRS'),
    "LRS_USER" => env('SEED_LRS_USER'),
    "NOTES" => env('SEED_NOTES'),
    "PERSONS" => env('SEED_PERSONS'),
    "RECORDINGS" => env('SEED_RECORDINGS'),
    "RECORDING_TAG" => env('SEED_RECORDING_TAG'),
    "RECORDING_VERSE" => env('RECORDING_VERSE'),
    "REPORTS" => env('SEED_REPORTS'),
    "SITES" => env('SEED_SITES'),
    "STATEMENTS" => env('SEED_STATEMENTS'),
    "STEPS" => env('SEED_STEPS'),
    "TESTS" => env('SEED_TESTS'),
    "TRANSCRIPTS" => env('SEED_TRANSCRIPTS')
];
